/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
});
export const TableReservation = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'guests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllTableReservations' : IDL.Func(
      [],
      [IDL.Vec(TableReservation)],
      ['query'],
    ),
  'reserveTable' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
  });
  const TableReservation = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'guests' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllTableReservations' : IDL.Func(
        [],
        [IDL.Vec(TableReservation)],
        ['query'],
      ),
    'reserveTable' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };